google_analytics_id: UA-33449675-1

repository: https://github.com/iROCKBUNNY/iROCKBUNNY

timezone: Asia/Shanghai

title: iROCKBUNNY
description: Official Website
url: https://irockbunny.com

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net

contact: contact[at]irockbunny[dot]com
github: https://github.com/iROCKBUNNY

image: /img/Avatar.png
logo: /img/Avatar.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor